# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [2]:
#todo: 
# Creamos un array con los números del 0 al 9 utilizando la función arange()
array_numeros_0_al_9 = np.arange(10)

# Mostramos el array generado
print("Array con los números del 0 al 9:", array_numeros_0_al_9)

Array con los números del 0 al 9: [0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [3]:
#todo:
# Creamos un array de 5 ceros utilizando np.zeros()
array_ceros = np.zeros(5)

# Modificamos el tercer elemento (índice 2) para que sea 5
array_ceros[2] = 5

# Mostramos el array resultante
print("Array después de modificar el tercer elemento:", array_ceros)

Array después de modificar el tercer elemento: [0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [4]:
#todo: 
# Utilizamos la función np.random.rand() para generar una matriz 3x3 con valores aleatorios
matriz_aleatoria_3x3 = np.random.rand(3, 3)

# Mostramos la matriz generada
print("Matriz 3x3 con números aleatorios entre 0 y 1:")
print(matriz_aleatoria_3x3)

Matriz 3x3 con números aleatorios entre 0 y 1:
[[0.82979203 0.36602979 0.39844794]
 [0.1910638  0.52291598 0.78704339]
 [0.00820327 0.75681968 0.84520321]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:

**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:

**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 

